//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdminResponseDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminResponseDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CommonGrp" type="{com/fiserv/Merchant/gmfV10.02}CommonGrp" minOccurs="0"/>
 *         &lt;element name="CardGrp" type="{com/fiserv/Merchant/gmfV10.02}CardGrp" minOccurs="0"/>
 *         &lt;element name="PINGrp" type="{com/fiserv/Merchant/gmfV10.02}PINGrp" minOccurs="0"/>
 *         &lt;element name="AddtlAmtGrp" type="{com/fiserv/Merchant/gmfV10.02}AddtlAmtGrp" maxOccurs="6" minOccurs="0"/>
 *         &lt;element name="TAGrp" type="{com/fiserv/Merchant/gmfV10.02}TAGrp" minOccurs="0"/>
 *         &lt;element name="CanDebitGrp" type="{com/fiserv/Merchant/gmfV10.02}CanDebitGrp" minOccurs="0"/>
 *         &lt;element name="StoredValueGrp" type="{com/fiserv/Merchant/gmfV10.02}StoredValueGrp" minOccurs="0"/>
 *         &lt;element name="RespGrp" type="{com/fiserv/Merchant/gmfV10.02}RespGrp" minOccurs="0"/>
 *         &lt;element name="HostTotGrp" type="{com/fiserv/Merchant/gmfV10.02}HostTotGrp" minOccurs="0"/>
 *         &lt;element name="HostTotDetGrp" type="{com/fiserv/Merchant/gmfV10.02}HostTotDetGrp" maxOccurs="29" minOccurs="0"/>
 *         &lt;element name="FileDLGrp" type="{com/fiserv/Merchant/gmfV10.02}FileDLGrp" minOccurs="0"/>
 *         &lt;element name="TLGrp" type="{com/fiserv/Merchant/gmfV10.02}TLGrp" maxOccurs="40" minOccurs="0"/>
 *         &lt;element name="RctTxtDetGrp" type="{com/fiserv/Merchant/gmfV10.02}RctTxtDetGrp" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="HostDiscDetGrp" type="{com/fiserv/Merchant/gmfV10.02}HostDiscDetGrp" maxOccurs="50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminResponseDetails", propOrder = {
    "commonGrp",
    "cardGrp",
    "pinGrp",
    "addtlAmtGrp",
    "taGrp",
    "canDebitGrp",
    "storedValueGrp",
    "respGrp",
    "hostTotGrp",
    "hostTotDetGrp",
    "fileDLGrp",
    "tlGrp",
    "rctTxtDetGrp",
    "hostDiscDetGrp"
})
public class AdminResponseDetails {

    @XmlElement(name = "CommonGrp")
    protected CommonGrp commonGrp;
    @XmlElement(name = "CardGrp")
    protected CardGrp cardGrp;
    @XmlElement(name = "PINGrp")
    protected PINGrp pinGrp;
    @XmlElement(name = "AddtlAmtGrp")
    protected List<AddtlAmtGrp> addtlAmtGrp;
    @XmlElement(name = "TAGrp")
    protected TAGrp taGrp;
    @XmlElement(name = "CanDebitGrp")
    protected CanDebitGrp canDebitGrp;
    @XmlElement(name = "StoredValueGrp")
    protected StoredValueGrp storedValueGrp;
    @XmlElement(name = "RespGrp")
    protected RespGrp respGrp;
    @XmlElement(name = "HostTotGrp")
    protected HostTotGrp hostTotGrp;
    @XmlElement(name = "HostTotDetGrp")
    protected List<HostTotDetGrp> hostTotDetGrp;
    @XmlElement(name = "FileDLGrp")
    protected FileDLGrp fileDLGrp;
    @XmlElement(name = "TLGrp")
    protected List<TLGrp> tlGrp;
    @XmlElement(name = "RctTxtDetGrp")
    protected List<RctTxtDetGrp> rctTxtDetGrp;
    @XmlElement(name = "HostDiscDetGrp")
    protected List<HostDiscDetGrp> hostDiscDetGrp;

    /**
     * Gets the value of the commonGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CommonGrp }
     *     
     */
    public CommonGrp getCommonGrp() {
        return commonGrp;
    }

    /**
     * Sets the value of the commonGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonGrp }
     *     
     */
    public void setCommonGrp(CommonGrp value) {
        this.commonGrp = value;
    }

    /**
     * Gets the value of the cardGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CardGrp }
     *     
     */
    public CardGrp getCardGrp() {
        return cardGrp;
    }

    /**
     * Sets the value of the cardGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardGrp }
     *     
     */
    public void setCardGrp(CardGrp value) {
        this.cardGrp = value;
    }

    /**
     * Gets the value of the pinGrp property.
     * 
     * @return
     *     possible object is
     *     {@link PINGrp }
     *     
     */
    public PINGrp getPINGrp() {
        return pinGrp;
    }

    /**
     * Sets the value of the pinGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PINGrp }
     *     
     */
    public void setPINGrp(PINGrp value) {
        this.pinGrp = value;
    }

    /**
     * Gets the value of the addtlAmtGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addtlAmtGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddtlAmtGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddtlAmtGrp }
     * 
     * 
     */
    public List<AddtlAmtGrp> getAddtlAmtGrp() {
        if (addtlAmtGrp == null) {
            addtlAmtGrp = new ArrayList<AddtlAmtGrp>();
        }
        return this.addtlAmtGrp;
    }

    /**
     * Gets the value of the taGrp property.
     * 
     * @return
     *     possible object is
     *     {@link TAGrp }
     *     
     */
    public TAGrp getTAGrp() {
        return taGrp;
    }

    /**
     * Sets the value of the taGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAGrp }
     *     
     */
    public void setTAGrp(TAGrp value) {
        this.taGrp = value;
    }

    /**
     * Gets the value of the canDebitGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CanDebitGrp }
     *     
     */
    public CanDebitGrp getCanDebitGrp() {
        return canDebitGrp;
    }

    /**
     * Sets the value of the canDebitGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CanDebitGrp }
     *     
     */
    public void setCanDebitGrp(CanDebitGrp value) {
        this.canDebitGrp = value;
    }

    /**
     * Gets the value of the storedValueGrp property.
     * 
     * @return
     *     possible object is
     *     {@link StoredValueGrp }
     *     
     */
    public StoredValueGrp getStoredValueGrp() {
        return storedValueGrp;
    }

    /**
     * Sets the value of the storedValueGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoredValueGrp }
     *     
     */
    public void setStoredValueGrp(StoredValueGrp value) {
        this.storedValueGrp = value;
    }

    /**
     * Gets the value of the respGrp property.
     * 
     * @return
     *     possible object is
     *     {@link RespGrp }
     *     
     */
    public RespGrp getRespGrp() {
        return respGrp;
    }

    /**
     * Sets the value of the respGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespGrp }
     *     
     */
    public void setRespGrp(RespGrp value) {
        this.respGrp = value;
    }

    /**
     * Gets the value of the hostTotGrp property.
     * 
     * @return
     *     possible object is
     *     {@link HostTotGrp }
     *     
     */
    public HostTotGrp getHostTotGrp() {
        return hostTotGrp;
    }

    /**
     * Sets the value of the hostTotGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostTotGrp }
     *     
     */
    public void setHostTotGrp(HostTotGrp value) {
        this.hostTotGrp = value;
    }

    /**
     * Gets the value of the hostTotDetGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostTotDetGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostTotDetGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HostTotDetGrp }
     * 
     * 
     */
    public List<HostTotDetGrp> getHostTotDetGrp() {
        if (hostTotDetGrp == null) {
            hostTotDetGrp = new ArrayList<HostTotDetGrp>();
        }
        return this.hostTotDetGrp;
    }

    /**
     * Gets the value of the fileDLGrp property.
     * 
     * @return
     *     possible object is
     *     {@link FileDLGrp }
     *     
     */
    public FileDLGrp getFileDLGrp() {
        return fileDLGrp;
    }

    /**
     * Sets the value of the fileDLGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileDLGrp }
     *     
     */
    public void setFileDLGrp(FileDLGrp value) {
        this.fileDLGrp = value;
    }

    /**
     * Gets the value of the tlGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tlGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTLGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TLGrp }
     * 
     * 
     */
    public List<TLGrp> getTLGrp() {
        if (tlGrp == null) {
            tlGrp = new ArrayList<TLGrp>();
        }
        return this.tlGrp;
    }

    /**
     * Gets the value of the rctTxtDetGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rctTxtDetGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRctTxtDetGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RctTxtDetGrp }
     * 
     * 
     */
    public List<RctTxtDetGrp> getRctTxtDetGrp() {
        if (rctTxtDetGrp == null) {
            rctTxtDetGrp = new ArrayList<RctTxtDetGrp>();
        }
        return this.rctTxtDetGrp;
    }

    /**
     * Gets the value of the hostDiscDetGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostDiscDetGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostDiscDetGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HostDiscDetGrp }
     * 
     * 
     */
    public List<HostDiscDetGrp> getHostDiscDetGrp() {
        if (hostDiscDetGrp == null) {
            hostDiscDetGrp = new ArrayList<HostDiscDetGrp>();
        }
        return this.hostDiscDetGrp;
    }

}
