//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BatchGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatchGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}BatchID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}SettleTxnType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}BatchProdCd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}BatchSeqNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}BatchL3Cnt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}BatchTktNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}RPS" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}InstSeqCt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}InstSeqNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PrintInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}BatchCt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}BatchAmt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatchGrp", propOrder = {
    "batchID",
    "settleTxnType",
    "batchProdCd",
    "batchSeqNum",
    "batchL3Cnt",
    "batchTktNum",
    "rps",
    "instSeqCt",
    "instSeqNum",
    "printInd",
    "batchCt",
    "batchAmt"
})
public class BatchGrp {

    @XmlElement(name = "BatchID")
    protected String batchID;
    @XmlElement(name = "SettleTxnType")
    protected String settleTxnType;
    @XmlElement(name = "BatchProdCd")
    protected String batchProdCd;
    @XmlElement(name = "BatchSeqNum")
    @XmlSchemaType(name = "integer")
    protected Integer batchSeqNum;
    @XmlElement(name = "BatchL3Cnt")
    protected String batchL3Cnt;
    @XmlElement(name = "BatchTktNum")
    protected String batchTktNum;
    @XmlElement(name = "RPS")
    protected String rps;
    @XmlElement(name = "InstSeqCt")
    @XmlSchemaType(name = "integer")
    protected Integer instSeqCt;
    @XmlElement(name = "InstSeqNum")
    @XmlSchemaType(name = "integer")
    protected Integer instSeqNum;
    @XmlElement(name = "PrintInd")
    @XmlSchemaType(name = "string")
    protected PrintIndType printInd;
    @XmlElement(name = "BatchCt")
    @XmlSchemaType(name = "integer")
    protected Integer batchCt;
    @XmlElement(name = "BatchAmt")
    protected String batchAmt;

    /**
     * Gets the value of the batchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchID() {
        return batchID;
    }

    /**
     * Sets the value of the batchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchID(String value) {
        this.batchID = value;
    }

    /**
     * Gets the value of the settleTxnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettleTxnType() {
        return settleTxnType;
    }

    /**
     * Sets the value of the settleTxnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettleTxnType(String value) {
        this.settleTxnType = value;
    }

    /**
     * Gets the value of the batchProdCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchProdCd() {
        return batchProdCd;
    }

    /**
     * Sets the value of the batchProdCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchProdCd(String value) {
        this.batchProdCd = value;
    }

    /**
     * Gets the value of the batchSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBatchSeqNum() {
        return batchSeqNum;
    }

    /**
     * Sets the value of the batchSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBatchSeqNum(Integer value) {
        this.batchSeqNum = value;
    }

    /**
     * Gets the value of the batchL3Cnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchL3Cnt() {
        return batchL3Cnt;
    }

    /**
     * Sets the value of the batchL3Cnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchL3Cnt(String value) {
        this.batchL3Cnt = value;
    }

    /**
     * Gets the value of the batchTktNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchTktNum() {
        return batchTktNum;
    }

    /**
     * Sets the value of the batchTktNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchTktNum(String value) {
        this.batchTktNum = value;
    }

    /**
     * Gets the value of the rps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRPS() {
        return rps;
    }

    /**
     * Sets the value of the rps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRPS(String value) {
        this.rps = value;
    }

    /**
     * Gets the value of the instSeqCt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInstSeqCt() {
        return instSeqCt;
    }

    /**
     * Sets the value of the instSeqCt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInstSeqCt(Integer value) {
        this.instSeqCt = value;
    }

    /**
     * Gets the value of the instSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInstSeqNum() {
        return instSeqNum;
    }

    /**
     * Sets the value of the instSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInstSeqNum(Integer value) {
        this.instSeqNum = value;
    }

    /**
     * Gets the value of the printInd property.
     * 
     * @return
     *     possible object is
     *     {@link PrintIndType }
     *     
     */
    public PrintIndType getPrintInd() {
        return printInd;
    }

    /**
     * Sets the value of the printInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintIndType }
     *     
     */
    public void setPrintInd(PrintIndType value) {
        this.printInd = value;
    }

    /**
     * Gets the value of the batchCt property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBatchCt() {
        return batchCt;
    }

    /**
     * Sets the value of the batchCt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBatchCt(Integer value) {
        this.batchCt = value;
    }

    /**
     * Gets the value of the batchAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchAmt() {
        return batchAmt;
    }

    /**
     * Sets the value of the batchAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchAmt(String value) {
        this.batchAmt = value;
    }

}
