//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPymtTxnIndType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BillPymtTxnIndType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV10.02}Max12AN">
 *     &lt;enumeration value="Single"/>
 *     &lt;enumeration value="Recurring"/>
 *     &lt;enumeration value="Installment"/>
 *     &lt;enumeration value="Deferred"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BillPymtTxnIndType")
@XmlEnum
public enum BillPymtTxnIndType {

    @XmlEnumValue("Single")
    SINGLE("Single"),
    @XmlEnumValue("Recurring")
    RECURRING("Recurring"),
    @XmlEnumValue("Installment")
    INSTALLMENT("Installment"),
    @XmlEnumValue("Deferred")
    DEFERRED("Deferred");
    private final String value;

    BillPymtTxnIndType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BillPymtTxnIndType fromValue(String v) {
        for (BillPymtTxnIndType c: BillPymtTxnIndType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
