//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardTypeType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV10.02}Max10AN">
 *     &lt;enumeration value="Amex"/>
 *     &lt;enumeration value="Diners"/>
 *     &lt;enumeration value="Discover"/>
 *     &lt;enumeration value="JCB"/>
 *     &lt;enumeration value="MaestroInt"/>
 *     &lt;enumeration value="MasterCard"/>
 *     &lt;enumeration value="Visa"/>
 *     &lt;enumeration value="GiftCard"/>
 *     &lt;enumeration value="PPayCL"/>
 *     &lt;enumeration value="CarCareOne"/>
 *     &lt;enumeration value="CostPlus"/>
 *     &lt;enumeration value="Dicks"/>
 *     &lt;enumeration value="Exxon"/>
 *     &lt;enumeration value="GenProp"/>
 *     &lt;enumeration value="Gulf"/>
 *     &lt;enumeration value="Shell"/>
 *     &lt;enumeration value="Sinclair"/>
 *     &lt;enumeration value="SpeedPass"/>
 *     &lt;enumeration value="Sunoco"/>
 *     &lt;enumeration value="ValeroUCC"/>
 *     &lt;enumeration value="Mexican"/>
 *     &lt;enumeration value="BPBusiness"/>
 *     &lt;enumeration value="Buypass"/>
 *     &lt;enumeration value="EssoFleet"/>
 *     &lt;enumeration value="ExxonFleet"/>
 *     &lt;enumeration value="FleetCor"/>
 *     &lt;enumeration value="FleetOne"/>
 *     &lt;enumeration value="MCFleet"/>
 *     &lt;enumeration value="UnionPay"/>
 *     &lt;enumeration value="ValeroFlt"/>
 *     &lt;enumeration value="VisaFleet"/>
 *     &lt;enumeration value="Voyager"/>
 *     &lt;enumeration value="Wex"/>
 *     &lt;enumeration value="Paypal"/>
 *     &lt;enumeration value="NGFC"/>
 *     &lt;enumeration value="WexOTR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardTypeType")
@XmlEnum
public enum CardTypeType {

    @XmlEnumValue("Amex")
    AMEX("Amex"),
    @XmlEnumValue("Diners")
    DINERS("Diners"),
    @XmlEnumValue("Discover")
    DISCOVER("Discover"),
    JCB("JCB"),
    @XmlEnumValue("MaestroInt")
    MAESTRO_INT("MaestroInt"),
    @XmlEnumValue("MasterCard")
    MASTER_CARD("MasterCard"),
    @XmlEnumValue("Visa")
    VISA("Visa"),
    @XmlEnumValue("GiftCard")
    GIFT_CARD("GiftCard"),
    @XmlEnumValue("PPayCL")
    P_PAY_CL("PPayCL"),
    @XmlEnumValue("CarCareOne")
    CAR_CARE_ONE("CarCareOne"),
    @XmlEnumValue("CostPlus")
    COST_PLUS("CostPlus"),
    @XmlEnumValue("Dicks")
    DICKS("Dicks"),
    @XmlEnumValue("Exxon")
    EXXON("Exxon"),
    @XmlEnumValue("GenProp")
    GEN_PROP("GenProp"),
    @XmlEnumValue("Gulf")
    GULF("Gulf"),
    @XmlEnumValue("Shell")
    SHELL("Shell"),
    @XmlEnumValue("Sinclair")
    SINCLAIR("Sinclair"),
    @XmlEnumValue("SpeedPass")
    SPEED_PASS("SpeedPass"),
    @XmlEnumValue("Sunoco")
    SUNOCO("Sunoco"),
    @XmlEnumValue("ValeroUCC")
    VALERO_UCC("ValeroUCC"),
    @XmlEnumValue("Mexican")
    MEXICAN("Mexican"),
    @XmlEnumValue("BPBusiness")
    BP_BUSINESS("BPBusiness"),
    @XmlEnumValue("Buypass")
    BUYPASS("Buypass"),
    @XmlEnumValue("EssoFleet")
    ESSO_FLEET("EssoFleet"),
    @XmlEnumValue("ExxonFleet")
    EXXON_FLEET("ExxonFleet"),
    @XmlEnumValue("FleetCor")
    FLEET_COR("FleetCor"),
    @XmlEnumValue("FleetOne")
    FLEET_ONE("FleetOne"),
    @XmlEnumValue("MCFleet")
    MC_FLEET("MCFleet"),
    @XmlEnumValue("UnionPay")
    UNION_PAY("UnionPay"),
    @XmlEnumValue("ValeroFlt")
    VALERO_FLT("ValeroFlt"),
    @XmlEnumValue("VisaFleet")
    VISA_FLEET("VisaFleet"),
    @XmlEnumValue("Voyager")
    VOYAGER("Voyager"),
    @XmlEnumValue("Wex")
    WEX("Wex"),
    @XmlEnumValue("Paypal")
    PAYPAL("Paypal"),
    NGFC("NGFC"),
    @XmlEnumValue("WexOTR")
    WEX_OTR("WexOTR");
    private final String value;

    CardTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CardTypeType fromValue(String v) {
        for (CardTypeType c: CardTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
