//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CHIDMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CHIDMethodType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV10.02}Max10AN">
 *     &lt;enumeration value="MOTO"/>
 *     &lt;enumeration value="PIN"/>
 *     &lt;enumeration value="QuickServ"/>
 *     &lt;enumeration value="Signature"/>
 *     &lt;enumeration value="Unknwn"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CHIDMethodType")
@XmlEnum
public enum CHIDMethodType {

    MOTO("MOTO"),
    PIN("PIN"),
    @XmlEnumValue("QuickServ")
    QUICK_SERV("QuickServ"),
    @XmlEnumValue("Signature")
    SIGNATURE("Signature"),
    @XmlEnumValue("Unknwn")
    UNKNWN("Unknwn");
    private final String value;

    CHIDMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CHIDMethodType fromValue(String v) {
        for (CHIDMethodType c: CHIDMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
