//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncrptTrgtType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EncrptTrgtType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV10.02}Max10AN">
 *     &lt;enumeration value="Track1"/>
 *     &lt;enumeration value="Track2"/>
 *     &lt;enumeration value="BothTracks"/>
 *     &lt;enumeration value="PAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EncrptTrgtType")
@XmlEnum
public enum EncrptTrgtType {

    @XmlEnumValue("Track1")
    TRACK_1("Track1"),
    @XmlEnumValue("Track2")
    TRACK_2("Track2"),
    @XmlEnumValue("BothTracks")
    BOTH_TRACKS("BothTracks"),
    PAN("PAN");
    private final String value;

    EncrptTrgtType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EncrptTrgtType fromValue(String v) {
        for (EncrptTrgtType c: EncrptTrgtType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
