//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EWICBalInfoGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EWICBalInfoGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PBCatCd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PBSubCatCd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PBQty" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EWICBalInfoGrp", propOrder = {
    "pbCatCd",
    "pbSubCatCd",
    "pbQty"
})
public class EWICBalInfoGrp {

    @XmlElement(name = "PBCatCd")
    protected String pbCatCd;
    @XmlElement(name = "PBSubCatCd")
    protected String pbSubCatCd;
    @XmlElement(name = "PBQty")
    protected String pbQty;

    /**
     * Gets the value of the pbCatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBCatCd() {
        return pbCatCd;
    }

    /**
     * Sets the value of the pbCatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBCatCd(String value) {
        this.pbCatCd = value;
    }

    /**
     * Gets the value of the pbSubCatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBSubCatCd() {
        return pbSubCatCd;
    }

    /**
     * Sets the value of the pbSubCatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBSubCatCd(String value) {
        this.pbSubCatCd = value;
    }

    /**
     * Gets the value of the pbQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBQty() {
        return pbQty;
    }

    /**
     * Sets the value of the pbQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBQty(String value) {
        this.pbQty = value;
    }

}
