//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HostDiscDetGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostDiscDetGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDStrDt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDEndDt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDCardType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDBINBeg" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDBINEnd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDProdCd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDProdDiscAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDDiscType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDQtyLt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}HDProgDesc" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostDiscDetGrp", propOrder = {
    "hdStrDt",
    "hdEndDt",
    "hdCardType",
    "hdbinBeg",
    "hdbinEnd",
    "hdProdCd",
    "hdProdDiscAmt",
    "hdDiscType",
    "hdQtyLt",
    "hdProgDesc"
})
public class HostDiscDetGrp {

    @XmlElement(name = "HDStrDt")
    protected String hdStrDt;
    @XmlElement(name = "HDEndDt")
    protected String hdEndDt;
    @XmlElement(name = "HDCardType")
    protected String hdCardType;
    @XmlElement(name = "HDBINBeg")
    protected String hdbinBeg;
    @XmlElement(name = "HDBINEnd")
    protected String hdbinEnd;
    @XmlElement(name = "HDProdCd")
    protected String hdProdCd;
    @XmlElement(name = "HDProdDiscAmt")
    protected String hdProdDiscAmt;
    @XmlElement(name = "HDDiscType")
    protected String hdDiscType;
    @XmlElement(name = "HDQtyLt")
    protected String hdQtyLt;
    @XmlElement(name = "HDProgDesc")
    protected String hdProgDesc;

    /**
     * Gets the value of the hdStrDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDStrDt() {
        return hdStrDt;
    }

    /**
     * Sets the value of the hdStrDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDStrDt(String value) {
        this.hdStrDt = value;
    }

    /**
     * Gets the value of the hdEndDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDEndDt() {
        return hdEndDt;
    }

    /**
     * Sets the value of the hdEndDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDEndDt(String value) {
        this.hdEndDt = value;
    }

    /**
     * Gets the value of the hdCardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDCardType() {
        return hdCardType;
    }

    /**
     * Sets the value of the hdCardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDCardType(String value) {
        this.hdCardType = value;
    }

    /**
     * Gets the value of the hdbinBeg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDBINBeg() {
        return hdbinBeg;
    }

    /**
     * Sets the value of the hdbinBeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDBINBeg(String value) {
        this.hdbinBeg = value;
    }

    /**
     * Gets the value of the hdbinEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDBINEnd() {
        return hdbinEnd;
    }

    /**
     * Sets the value of the hdbinEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDBINEnd(String value) {
        this.hdbinEnd = value;
    }

    /**
     * Gets the value of the hdProdCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDProdCd() {
        return hdProdCd;
    }

    /**
     * Sets the value of the hdProdCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDProdCd(String value) {
        this.hdProdCd = value;
    }

    /**
     * Gets the value of the hdProdDiscAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDProdDiscAmt() {
        return hdProdDiscAmt;
    }

    /**
     * Sets the value of the hdProdDiscAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDProdDiscAmt(String value) {
        this.hdProdDiscAmt = value;
    }

    /**
     * Gets the value of the hdDiscType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDDiscType() {
        return hdDiscType;
    }

    /**
     * Sets the value of the hdDiscType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDDiscType(String value) {
        this.hdDiscType = value;
    }

    /**
     * Gets the value of the hdQtyLt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDQtyLt() {
        return hdQtyLt;
    }

    /**
     * Sets the value of the hdQtyLt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDQtyLt(String value) {
        this.hdQtyLt = value;
    }

    /**
     * Gets the value of the hdProgDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDProgDesc() {
        return hdProgDesc;
    }

    /**
     * Sets the value of the hdProgDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDProgDesc(String value) {
        this.hdProgDesc = value;
    }

}
