//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HostTotDetGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostTotDetGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}CardTag" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}TxnCt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}CardTxnAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}SumPymtTypeTag" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostTotDetGrp", propOrder = {
    "cardTag",
    "txnCt",
    "cardTxnAmt",
    "sumPymtTypeTag"
})
public class HostTotDetGrp {

    @XmlElement(name = "CardTag")
    @XmlSchemaType(name = "string")
    protected CardTagType cardTag;
    @XmlElement(name = "TxnCt")
    protected String txnCt;
    @XmlElement(name = "CardTxnAmt")
    protected String cardTxnAmt;
    @XmlElement(name = "SumPymtTypeTag")
    protected String sumPymtTypeTag;

    /**
     * Gets the value of the cardTag property.
     * 
     * @return
     *     possible object is
     *     {@link CardTagType }
     *     
     */
    public CardTagType getCardTag() {
        return cardTag;
    }

    /**
     * Sets the value of the cardTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardTagType }
     *     
     */
    public void setCardTag(CardTagType value) {
        this.cardTag = value;
    }

    /**
     * Gets the value of the txnCt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnCt() {
        return txnCt;
    }

    /**
     * Sets the value of the txnCt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnCt(String value) {
        this.txnCt = value;
    }

    /**
     * Gets the value of the cardTxnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTxnAmt() {
        return cardTxnAmt;
    }

    /**
     * Sets the value of the cardTxnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTxnAmt(String value) {
        this.cardTxnAmt = value;
    }

    /**
     * Gets the value of the sumPymtTypeTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSumPymtTypeTag() {
        return sumPymtTypeTag;
    }

    /**
     * Sets the value of the sumPymtTypeTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSumPymtTypeTag(String value) {
        this.sumPymtTypeTag = value;
    }

}
