//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MEXCardGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MEXCardGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}CHIDMethod" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DfrdPymtPlan" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}NumDfrdPymts" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DfrdPymtMonths" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}RctTxtResp" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PymtPlnCntrtNum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MEXCardGrp", propOrder = {
    "chidMethod",
    "dfrdPymtPlan",
    "numDfrdPymts",
    "dfrdPymtMonths",
    "rctTxtResp",
    "pymtPlnCntrtNum"
})
public class MEXCardGrp {

    @XmlElement(name = "CHIDMethod")
    @XmlSchemaType(name = "string")
    protected CHIDMethodType chidMethod;
    @XmlElement(name = "DfrdPymtPlan")
    @XmlSchemaType(name = "string")
    protected DfrdPymtPlanType dfrdPymtPlan;
    @XmlElement(name = "NumDfrdPymts")
    @XmlSchemaType(name = "integer")
    protected Integer numDfrdPymts;
    @XmlElement(name = "DfrdPymtMonths")
    @XmlSchemaType(name = "integer")
    protected Integer dfrdPymtMonths;
    @XmlElement(name = "RctTxtResp")
    protected String rctTxtResp;
    @XmlElement(name = "PymtPlnCntrtNum")
    protected String pymtPlnCntrtNum;

    /**
     * Gets the value of the chidMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CHIDMethodType }
     *     
     */
    public CHIDMethodType getCHIDMethod() {
        return chidMethod;
    }

    /**
     * Sets the value of the chidMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHIDMethodType }
     *     
     */
    public void setCHIDMethod(CHIDMethodType value) {
        this.chidMethod = value;
    }

    /**
     * Gets the value of the dfrdPymtPlan property.
     * 
     * @return
     *     possible object is
     *     {@link DfrdPymtPlanType }
     *     
     */
    public DfrdPymtPlanType getDfrdPymtPlan() {
        return dfrdPymtPlan;
    }

    /**
     * Sets the value of the dfrdPymtPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link DfrdPymtPlanType }
     *     
     */
    public void setDfrdPymtPlan(DfrdPymtPlanType value) {
        this.dfrdPymtPlan = value;
    }

    /**
     * Gets the value of the numDfrdPymts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumDfrdPymts() {
        return numDfrdPymts;
    }

    /**
     * Sets the value of the numDfrdPymts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumDfrdPymts(Integer value) {
        this.numDfrdPymts = value;
    }

    /**
     * Gets the value of the dfrdPymtMonths property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDfrdPymtMonths() {
        return dfrdPymtMonths;
    }

    /**
     * Sets the value of the dfrdPymtMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDfrdPymtMonths(Integer value) {
        this.dfrdPymtMonths = value;
    }

    /**
     * Gets the value of the rctTxtResp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRctTxtResp() {
        return rctTxtResp;
    }

    /**
     * Sets the value of the rctTxtResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRctTxtResp(String value) {
        this.rctTxtResp = value;
    }

    /**
     * Gets the value of the pymtPlnCntrtNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPymtPlnCntrtNum() {
        return pymtPlnCntrtNum;
    }

    /**
     * Sets the value of the pymtPlnCntrtNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPymtPlnCntrtNum(String value) {
        this.pymtPlnCntrtNum = value;
    }

}
