//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTRProdCatType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OTRProdCatType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV10.02}Max4AN">
 *     &lt;enumeration value="ADD"/>
 *     &lt;enumeration value="ANFR"/>
 *     &lt;enumeration value="BRAK"/>
 *     &lt;enumeration value="CADV"/>
 *     &lt;enumeration value="CLTH"/>
 *     &lt;enumeration value="DEF"/>
 *     &lt;enumeration value="DELI"/>
 *     &lt;enumeration value="ELEC"/>
 *     &lt;enumeration value="ETAX"/>
 *     &lt;enumeration value="FAX"/>
 *     &lt;enumeration value="FLAT"/>
 *     &lt;enumeration value="GROC"/>
 *     &lt;enumeration value="HARD"/>
 *     &lt;enumeration value="IDLE"/>
 *     &lt;enumeration value="LMPR"/>
 *     &lt;enumeration value="LUBE"/>
 *     &lt;enumeration value="MERC"/>
 *     &lt;enumeration value="OIL"/>
 *     &lt;enumeration value="OILC"/>
 *     &lt;enumeration value="PADV"/>
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="PHON"/>
 *     &lt;enumeration value="PNT"/>
 *     &lt;enumeration value="RECP"/>
 *     &lt;enumeration value="REPR"/>
 *     &lt;enumeration value="REST"/>
 *     &lt;enumeration value="SCAN"/>
 *     &lt;enumeration value="SCLE"/>
 *     &lt;enumeration value="SHWR"/>
 *     &lt;enumeration value="TCHN"/>
 *     &lt;enumeration value="TIRE"/>
 *     &lt;enumeration value="TOLL"/>
 *     &lt;enumeration value="TRAL"/>
 *     &lt;enumeration value="TRPP"/>
 *     &lt;enumeration value="UREA"/>
 *     &lt;enumeration value="WASH"/>
 *     &lt;enumeration value="WWFL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OTRProdCatType")
@XmlEnum
public enum OTRProdCatType {

    ADD,
    ANFR,
    BRAK,
    CADV,
    CLTH,
    DEF,
    DELI,
    ELEC,
    ETAX,
    FAX,
    FLAT,
    GROC,
    HARD,
    IDLE,
    LMPR,
    LUBE,
    MERC,
    OIL,
    OILC,
    PADV,
    PART,
    PHON,
    PNT,
    RECP,
    REPR,
    REST,
    SCAN,
    SCLE,
    SHWR,
    TCHN,
    TIRE,
    TOLL,
    TRAL,
    TRPP,
    UREA,
    WASH,
    WWFL;

    public String value() {
        return name();
    }

    public static OTRProdCatType fromValue(String v) {
        return valueOf(v);
    }

}
