//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OTRProdDetGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTRProdDetGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}OTRProdCat" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}OTRProdQty" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}OTRProdAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}OTRProdAmtLimit" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTRProdDetGrp", propOrder = {
    "otrProdCat",
    "otrProdQty",
    "otrProdAmt",
    "otrProdAmtLimit"
})
public class OTRProdDetGrp {

    @XmlElement(name = "OTRProdCat")
    @XmlSchemaType(name = "string")
    protected OTRProdCatType otrProdCat;
    @XmlElement(name = "OTRProdQty")
    protected String otrProdQty;
    @XmlElement(name = "OTRProdAmt")
    protected String otrProdAmt;
    @XmlElement(name = "OTRProdAmtLimit")
    protected String otrProdAmtLimit;

    /**
     * Gets the value of the otrProdCat property.
     * 
     * @return
     *     possible object is
     *     {@link OTRProdCatType }
     *     
     */
    public OTRProdCatType getOTRProdCat() {
        return otrProdCat;
    }

    /**
     * Sets the value of the otrProdCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTRProdCatType }
     *     
     */
    public void setOTRProdCat(OTRProdCatType value) {
        this.otrProdCat = value;
    }

    /**
     * Gets the value of the otrProdQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTRProdQty() {
        return otrProdQty;
    }

    /**
     * Sets the value of the otrProdQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTRProdQty(String value) {
        this.otrProdQty = value;
    }

    /**
     * Gets the value of the otrProdAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTRProdAmt() {
        return otrProdAmt;
    }

    /**
     * Sets the value of the otrProdAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTRProdAmt(String value) {
        this.otrProdAmt = value;
    }

    /**
     * Gets the value of the otrProdAmtLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTRProdAmtLimit() {
        return otrProdAmtLimit;
    }

    /**
     * Sets the value of the otrProdAmtLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTRProdAmtLimit(String value) {
        this.otrProdAmtLimit = value;
    }

}
