//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrvLblGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrvLblGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}SpdPssID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DSTChlngInpt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DSTChlngRsp" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}LgValPrd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ActAcctNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ActExpiryDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrvLblGrp", propOrder = {
    "spdPssID",
    "dstChlngInpt",
    "dstChlngRsp",
    "lgValPrd",
    "actAcctNum",
    "actExpiryDate"
})
public class PrvLblGrp {

    @XmlElement(name = "SpdPssID")
    protected String spdPssID;
    @XmlElement(name = "DSTChlngInpt")
    protected String dstChlngInpt;
    @XmlElement(name = "DSTChlngRsp")
    protected String dstChlngRsp;
    @XmlElement(name = "LgValPrd")
    protected String lgValPrd;
    @XmlElement(name = "ActAcctNum")
    protected String actAcctNum;
    @XmlElement(name = "ActExpiryDate")
    protected String actExpiryDate;

    /**
     * Gets the value of the spdPssID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpdPssID() {
        return spdPssID;
    }

    /**
     * Sets the value of the spdPssID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpdPssID(String value) {
        this.spdPssID = value;
    }

    /**
     * Gets the value of the dstChlngInpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSTChlngInpt() {
        return dstChlngInpt;
    }

    /**
     * Sets the value of the dstChlngInpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSTChlngInpt(String value) {
        this.dstChlngInpt = value;
    }

    /**
     * Gets the value of the dstChlngRsp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSTChlngRsp() {
        return dstChlngRsp;
    }

    /**
     * Sets the value of the dstChlngRsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSTChlngRsp(String value) {
        this.dstChlngRsp = value;
    }

    /**
     * Gets the value of the lgValPrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLgValPrd() {
        return lgValPrd;
    }

    /**
     * Sets the value of the lgValPrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLgValPrd(String value) {
        this.lgValPrd = value;
    }

    /**
     * Gets the value of the actAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActAcctNum() {
        return actAcctNum;
    }

    /**
     * Sets the value of the actAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActAcctNum(String value) {
        this.actAcctNum = value;
    }

    /**
     * Gets the value of the actExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActExpiryDate() {
        return actExpiryDate;
    }

    /**
     * Sets the value of the actExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActExpiryDate(String value) {
        this.actExpiryDate = value;
    }

}
