//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PurchCardlvl2Grp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchCardlvl2Grp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}TaxAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}TaxInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}VATTaxAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}VATTaxRt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PurchIdfr" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PCOrderNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DiscntAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}FrghtAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DutyAmt" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DestPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ShipFromPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DestCtryCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}MerchTaxID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ProdDesc" maxOccurs="4" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PC3Add" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}MerchRefNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}MerchType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DestStCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ComCardType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ReqstrName" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ReqstrAddr" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchCardlvl2Grp", propOrder = {
    "taxAmt",
    "taxInd",
    "vatTaxAmt",
    "vatTaxRt",
    "purchIdfr",
    "pcOrderNum",
    "discntAmt",
    "frghtAmt",
    "dutyAmt",
    "destPostalCode",
    "shipFromPostalCode",
    "destCtryCode",
    "merchTaxID",
    "prodDesc",
    "pc3Add",
    "merchRefNum",
    "merchType",
    "destStCode",
    "comCardType",
    "reqstrName",
    "reqstrAddr"
})
public class PurchCardlvl2Grp {

    @XmlElement(name = "TaxAmt")
    protected String taxAmt;
    @XmlElement(name = "TaxInd")
    protected String taxInd;
    @XmlElement(name = "VATTaxAmt")
    protected String vatTaxAmt;
    @XmlElement(name = "VATTaxRt")
    protected String vatTaxRt;
    @XmlElement(name = "PurchIdfr")
    protected String purchIdfr;
    @XmlElement(name = "PCOrderNum")
    protected String pcOrderNum;
    @XmlElement(name = "DiscntAmt")
    protected String discntAmt;
    @XmlElement(name = "FrghtAmt")
    protected String frghtAmt;
    @XmlElement(name = "DutyAmt")
    protected String dutyAmt;
    @XmlElement(name = "DestPostalCode")
    protected String destPostalCode;
    @XmlElement(name = "ShipFromPostalCode")
    protected String shipFromPostalCode;
    @XmlElement(name = "DestCtryCode")
    protected String destCtryCode;
    @XmlElement(name = "MerchTaxID")
    protected String merchTaxID;
    @XmlElement(name = "ProdDesc")
    protected List<String> prodDesc;
    @XmlElement(name = "PC3Add")
    protected String pc3Add;
    @XmlElement(name = "MerchRefNum")
    protected String merchRefNum;
    @XmlElement(name = "MerchType")
    protected String merchType;
    @XmlElement(name = "DestStCode")
    protected String destStCode;
    @XmlElement(name = "ComCardType")
    protected String comCardType;
    @XmlElement(name = "ReqstrName")
    protected String reqstrName;
    @XmlElement(name = "ReqstrAddr")
    protected String reqstrAddr;

    /**
     * Gets the value of the taxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAmt() {
        return taxAmt;
    }

    /**
     * Sets the value of the taxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAmt(String value) {
        this.taxAmt = value;
    }

    /**
     * Gets the value of the taxInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxInd() {
        return taxInd;
    }

    /**
     * Sets the value of the taxInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxInd(String value) {
        this.taxInd = value;
    }

    /**
     * Gets the value of the vatTaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATTaxAmt() {
        return vatTaxAmt;
    }

    /**
     * Sets the value of the vatTaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATTaxAmt(String value) {
        this.vatTaxAmt = value;
    }

    /**
     * Gets the value of the vatTaxRt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATTaxRt() {
        return vatTaxRt;
    }

    /**
     * Sets the value of the vatTaxRt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATTaxRt(String value) {
        this.vatTaxRt = value;
    }

    /**
     * Gets the value of the purchIdfr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchIdfr() {
        return purchIdfr;
    }

    /**
     * Sets the value of the purchIdfr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchIdfr(String value) {
        this.purchIdfr = value;
    }

    /**
     * Gets the value of the pcOrderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCOrderNum() {
        return pcOrderNum;
    }

    /**
     * Sets the value of the pcOrderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCOrderNum(String value) {
        this.pcOrderNum = value;
    }

    /**
     * Gets the value of the discntAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscntAmt() {
        return discntAmt;
    }

    /**
     * Sets the value of the discntAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscntAmt(String value) {
        this.discntAmt = value;
    }

    /**
     * Gets the value of the frghtAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrghtAmt() {
        return frghtAmt;
    }

    /**
     * Sets the value of the frghtAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrghtAmt(String value) {
        this.frghtAmt = value;
    }

    /**
     * Gets the value of the dutyAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutyAmt() {
        return dutyAmt;
    }

    /**
     * Sets the value of the dutyAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutyAmt(String value) {
        this.dutyAmt = value;
    }

    /**
     * Gets the value of the destPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestPostalCode() {
        return destPostalCode;
    }

    /**
     * Sets the value of the destPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestPostalCode(String value) {
        this.destPostalCode = value;
    }

    /**
     * Gets the value of the shipFromPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipFromPostalCode() {
        return shipFromPostalCode;
    }

    /**
     * Sets the value of the shipFromPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipFromPostalCode(String value) {
        this.shipFromPostalCode = value;
    }

    /**
     * Gets the value of the destCtryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestCtryCode() {
        return destCtryCode;
    }

    /**
     * Sets the value of the destCtryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestCtryCode(String value) {
        this.destCtryCode = value;
    }

    /**
     * Gets the value of the merchTaxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchTaxID() {
        return merchTaxID;
    }

    /**
     * Sets the value of the merchTaxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchTaxID(String value) {
        this.merchTaxID = value;
    }

    /**
     * Gets the value of the prodDesc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prodDesc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProdDesc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProdDesc() {
        if (prodDesc == null) {
            prodDesc = new ArrayList<String>();
        }
        return this.prodDesc;
    }

    /**
     * Gets the value of the pc3Add property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3Add() {
        return pc3Add;
    }

    /**
     * Sets the value of the pc3Add property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3Add(String value) {
        this.pc3Add = value;
    }

    /**
     * Gets the value of the merchRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchRefNum() {
        return merchRefNum;
    }

    /**
     * Sets the value of the merchRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchRefNum(String value) {
        this.merchRefNum = value;
    }

    /**
     * Gets the value of the merchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchType() {
        return merchType;
    }

    /**
     * Sets the value of the merchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchType(String value) {
        this.merchType = value;
    }

    /**
     * Gets the value of the destStCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestStCode() {
        return destStCode;
    }

    /**
     * Sets the value of the destStCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestStCode(String value) {
        this.destStCode = value;
    }

    /**
     * Gets the value of the comCardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComCardType() {
        return comCardType;
    }

    /**
     * Sets the value of the comCardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComCardType(String value) {
        this.comCardType = value;
    }

    /**
     * Gets the value of the reqstrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqstrName() {
        return reqstrName;
    }

    /**
     * Sets the value of the reqstrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqstrName(String value) {
        this.reqstrName = value;
    }

    /**
     * Gets the value of the reqstrAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqstrAddr() {
        return reqstrAddr;
    }

    /**
     * Sets the value of the reqstrAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqstrAddr(String value) {
        this.reqstrAddr = value;
    }

}
