//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RctTxtDetGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RctTxtDetGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}RctTxtData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RctTxtDetGrp", propOrder = {
    "rctTxtData"
})
public class RctTxtDetGrp {

    @XmlElement(name = "RctTxtData")
    protected String rctTxtData;

    /**
     * Gets the value of the rctTxtData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRctTxtData() {
        return rctTxtData;
    }

    /**
     * Sets the value of the rctTxtData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRctTxtData(String value) {
        this.rctTxtData = value;
    }

}
