//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}RespCode" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}AuthID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ResponseDate" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}AddtlRespData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}SttlmDate" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}AthNtwkID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}AthNtwkNm" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}RtInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}SigInd" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}ErrorData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}DebitTraceNum" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}AthNtwkTrcID" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}SettlementTxnType" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}PrintData" minOccurs="0"/>
 *         &lt;element ref="{com/fiserv/Merchant/gmfV10.02}AssocRespCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespGrp", propOrder = {
    "respCode",
    "authID",
    "responseDate",
    "addtlRespData",
    "sttlmDate",
    "athNtwkID",
    "athNtwkNm",
    "rtInd",
    "sigInd",
    "errorData",
    "debitTraceNum",
    "athNtwkTrcID",
    "settlementTxnType",
    "printData",
    "assocRespCode"
})
public class RespGrp {

    @XmlElement(name = "RespCode")
    protected String respCode;
    @XmlElement(name = "AuthID")
    protected String authID;
    @XmlElement(name = "ResponseDate")
    protected String responseDate;
    @XmlElement(name = "AddtlRespData")
    protected String addtlRespData;
    @XmlElement(name = "SttlmDate")
    protected String sttlmDate;
    @XmlElement(name = "AthNtwkID")
    protected String athNtwkID;
    @XmlElement(name = "AthNtwkNm")
    protected String athNtwkNm;
    @XmlElement(name = "RtInd")
    protected String rtInd;
    @XmlElement(name = "SigInd")
    protected String sigInd;
    @XmlElement(name = "ErrorData")
    protected String errorData;
    @XmlElement(name = "DebitTraceNum")
    protected String debitTraceNum;
    @XmlElement(name = "AthNtwkTrcID")
    protected String athNtwkTrcID;
    @XmlElement(name = "SettlementTxnType")
    protected String settlementTxnType;
    @XmlElement(name = "PrintData")
    protected String printData;
    @XmlElement(name = "AssocRespCode")
    protected String assocRespCode;

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the authID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthID() {
        return authID;
    }

    /**
     * Sets the value of the authID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthID(String value) {
        this.authID = value;
    }

    /**
     * Gets the value of the responseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseDate() {
        return responseDate;
    }

    /**
     * Sets the value of the responseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseDate(String value) {
        this.responseDate = value;
    }

    /**
     * Gets the value of the addtlRespData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddtlRespData() {
        return addtlRespData;
    }

    /**
     * Sets the value of the addtlRespData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddtlRespData(String value) {
        this.addtlRespData = value;
    }

    /**
     * Gets the value of the sttlmDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSttlmDate() {
        return sttlmDate;
    }

    /**
     * Sets the value of the sttlmDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSttlmDate(String value) {
        this.sttlmDate = value;
    }

    /**
     * Gets the value of the athNtwkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAthNtwkID() {
        return athNtwkID;
    }

    /**
     * Sets the value of the athNtwkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAthNtwkID(String value) {
        this.athNtwkID = value;
    }

    /**
     * Gets the value of the athNtwkNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAthNtwkNm() {
        return athNtwkNm;
    }

    /**
     * Sets the value of the athNtwkNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAthNtwkNm(String value) {
        this.athNtwkNm = value;
    }

    /**
     * Gets the value of the rtInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtInd() {
        return rtInd;
    }

    /**
     * Sets the value of the rtInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtInd(String value) {
        this.rtInd = value;
    }

    /**
     * Gets the value of the sigInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigInd() {
        return sigInd;
    }

    /**
     * Sets the value of the sigInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigInd(String value) {
        this.sigInd = value;
    }

    /**
     * Gets the value of the errorData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorData() {
        return errorData;
    }

    /**
     * Sets the value of the errorData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorData(String value) {
        this.errorData = value;
    }

    /**
     * Gets the value of the debitTraceNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitTraceNum() {
        return debitTraceNum;
    }

    /**
     * Sets the value of the debitTraceNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitTraceNum(String value) {
        this.debitTraceNum = value;
    }

    /**
     * Gets the value of the athNtwkTrcID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAthNtwkTrcID() {
        return athNtwkTrcID;
    }

    /**
     * Sets the value of the athNtwkTrcID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAthNtwkTrcID(String value) {
        this.athNtwkTrcID = value;
    }

    /**
     * Gets the value of the settlementTxnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementTxnType() {
        return settlementTxnType;
    }

    /**
     * Sets the value of the settlementTxnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementTxnType(String value) {
        this.settlementTxnType = value;
    }

    /**
     * Gets the value of the printData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintData() {
        return printData;
    }

    /**
     * Sets the value of the printData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintData(String value) {
        this.printData = value;
    }

    /**
     * Gets the value of the assocRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssocRespCode() {
        return assocRespCode;
    }

    /**
     * Sets the value of the assocRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssocRespCode(String value) {
        this.assocRespCode = value;
    }

}
