//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 03:21:12 PM EST 
//


package fiserv.rc.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TranInitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TranInitType">
 *   &lt;restriction base="{com/fiserv/Merchant/gmfV10.02}Len8AN">
 *     &lt;enumeration value="Merchant"/>
 *     &lt;enumeration value="Terminal"/>
 *     &lt;enumeration value="Customer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TranInitType")
@XmlEnum
public enum TranInitType {

    @XmlEnumValue("Merchant")
    MERCHANT("Merchant"),
    @XmlEnumValue("Terminal")
    TERMINAL("Terminal"),
    @XmlEnumValue("Customer")
    CUSTOMER("Customer");
    private final String value;

    TranInitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TranInitType fromValue(String v) {
        for (TranInitType c: TranInitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
